<header>
<form method="POST" action="index.php">
	<input type="submit" value="Connexion" name="login">
	<input type="password" required placeholder="Password" name="password">
	<input type="text" required placeholder="e-mail" name="email">
</form>
<form action="index.php" method="POST">
	<input type="submit" name="page_inscription" value="S'inscrire">
</form>
<h1><a href="index.php">Plantes <span class="green">Book</span></a></h1>
</header>