<?php include('sources/include/slider.phtml'); ?>
<div class="content-home">
<h2>Produits récents</h2>
	<div class="produit-recent">
		<?php
	require('models/produit.class.php'); 
	$listProduct = "SELECT * FROM produits LIMIT 0,10";

	if ($result = mysqli_query($db, $listProduct)) {

	    while ($obj = mysqli_fetch_object($result,"Produit")) {
	        echo "<div class='affProduit'> <form action='index.php' method='POST'><img class='ico-back' src='sources/images_load/".$obj->getPhoto()."'alt='img'> nom :". $obj->getNom()." description :". $obj->getDescription() ." prix :". $obj->getPrix() ."€ stock :". $obj->getStock()." <input type='hidden' name='idPanier' value='".$obj->getId()."'> <input type='submit' name='addPanier' value='Ajouter au panier'></form></div>";
	    }
	    mysqli_free_result($result);
	}
	$page="shop";
		?>
	</div>
</div>
