<?php include('sources/include/slider.phtml'); ?>
<div class="content-home">
<h2>Produits récents</h2>
	<div class="produit-recent">
		<?php
	require('models/produit.class.php'); 
	$listProduct = "SELECT * FROM produits LIMIT 0,6";

	if ($result = mysqli_query($db, $listProduct)) {

	    while ($obj = mysqli_fetch_object($result,"Produit")) {
	        	        require('views/fiche.phtml');
	    }
	    mysqli_free_result($result);
	}
	$page="shop";
		?>
	</div>
</div>
