<div class="inscription">
		<form action="index.php" method="POST">
			<h2>Inscription</h2>
			<input type="text" placeholder="Nom" name="add-nom" required><br/>
			<input type="text" placeholder="Prenom" name="add-prenom" required><br/>
			<input type="email" placeholder="E-mail" name="add-email" required><br/>
			<input type="password" placeholder="Mot de passe" name="add-password" required><br/><input type="submit" value="S'inscrire" name="add-user">
		</form>
</div>
