<div class="profil">
	<form action="index.php" method="POST">
		<h2>Mon compte</h2>
		<input type="text" name="nom" placeholder="nom" value="<?=$nom?>">
		<input type="text" name="prenom"  placeholder="prenom" value="<?=$prenom?>">
		<input type="text" name="email"  placeholder="email" value="<?=$email?>">
		<input type="text" name="rue" placeholder="rue" value="<?=$rue?>">
		<input type="number" name="numeroRue" placeholder="numero" value="<?=$numeroRue?>">
		<input type="text" name="ville" placeholder="ville" value="<?=$ville?>">
		<input type="number" name="codePostal" placeholder="code postal" value="<?=$codePostal?>">
		<input type="submit" class="bouton_sinscrire" name="profilModify" value="Enregistrer">
		<input type="submit" class="bouton_sinscrire" name="profilDelete" value="Supprimer le compte">
	</form>
</div>