<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="UTF-8">
	<title>Plantes Book</title>
	<link rel="stylesheet" type="text/css" href="sources/css/style.css">
	<link rel="stylesheet" type="text/css" href="sources/css/aff.css">
	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	<script src="sources/assets/js/jquery.js"></script>
	<link href="sources/assets/css/bootstrap.css" rel="stylesheet">
    <link href="sources/assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="sources/font-awesome/css/font-awesome.min.css">
	<script src="sources/js/ajax.js"></script>    
</head>
<body>
	<div class="content">
	<?php require("apps/".$header.".php"); ?>
	<?php require("views/nav.phtml"); ?>
	<?php require("apps/".$page.".php"); ?>
	<?php require("apps/footer.php"); ?>
	</div>
</body>
</html>