<!-- Button to trigger modal -->
    <a href="#myModal" role="button" data-toggle="modal"><i class="fa fa-shopping-cart fa-2x green"></i></a>
 
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Mon panier</h3>
    </div>
    <div class="modal-body">
    <form action="index.php" method="POST">
        <?php
        $prixTotal = "";
            if(isset($_SESSION['id'])) {
                $res = mysqli_query($db, "SELECT * FROM panier WHERE id_panier='".$_SESSION['id']."'");
                while($data = mysqli_fetch_assoc($res)) {
                    echo "<div class='produitPanier'><img class='ico-back' src='sources/images_load/".$data['photo']."'>".$data['nom']." - ".$data['prix']." € <input type='hidden' name='nomProduct' value='".$data['nom']."'> <input type='hidden' name='idProduct' value='".$data['id']."'><input type='submit' class='btn' name='deleteProduct' value='supprimer'></div>";

                        $prixTotal = $prixTotal + $data['prix'];
                 }
            }
            else {
                echo "Connectez-vous pour accéder à votre panier.";
            }
        ?>
        <p>Total :&nbsp;<?=$prixTotal?>&nbsp;€</p>
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    <!-- <button type="submit" name="payer" class="btn btn-primary">Payer</button> -->
    <input type="submit" name="payer" class="btn btn-primary" value="payer">
    </form>
    </div>
    </div>
    <script src="sources/assets/js/bootstrap-modal.js"></script>