<div class="slider">
	<div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
    <div class="active item"><img src="sources/images/header1.jpg" alt="img"></div>
    <div class="item"><img src="sources/images/header2.jpg" alt="img"></div>
    <div class="item"><img src="sources/images/header3.jpg" alt="img"></div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
    <script src="sources/assets/js/bootstrap-carousel.js"></script>
</div>